#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        02_get_all_tenant_details.yml 
# Author:       Adrian Bronder
# Date:         2020-06-23
# Description:  Get tenant information
#               with Ansible and REST APIs
#
# Modules:      URI (calling GRID REST APIs)
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://<GRID Admin>/grid/apidocs.html
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input_grid: &input_grid
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ grid_auth_response.json.data }}"
      validate_certs:          false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "username":            "{{ SG_ADMIN_USER }}",
        "password":            "{{ SG_ADMIN_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: grid_auth_response

  - name: Get Grid Tenants
    netapp.storagegrid.na_sg_grid_info:
      gather_subset: grid_accounts_info
      <<: *input_grid
    register: grid_tenants

  - name: Print GRID tenants
    debug:
      msg:
        - "Tenant:             {{ item.name }}"
        - "ID:                 {{ item.id }}"
        - "Capabilities:       {{ item.capabilities }}"
        - "Policy:             Platform Services: {{ item.policy.allowPlatformServices }}, \
                               Quota: {{ ((item.policy.quotaObjectBytes / 1000 | pow(3)) | int) if item.policy.quotaObjectBytes != none else '--' }} GB, \
                               Use Identity Source: {{ item.policy.useAccountIdentitySource }}"
    with_items:
      - "{{ grid_tenants.sg_info['grid/accounts'].data }}"
    loop_control:
      label: "{{ item.id }}"
