#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        02_get_tenant_details.yml 
# Author:       Adrian Bronder
# Date:         2020-06-23
# Description:  Get tenant information
#               with Ansible and REST APIs
#
# Modules:      URI (calling GRID REST APIs)
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://<GRID Admin>/grid/apidocs.html
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ auth_response.json.data }}"
      validate_certs:          false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url: "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method: POST
      body: {
        "username":            "{{ SG_ADMIN_USER }}",
        "password":            "{{ SG_ADMIN_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
      body_format: json
      validate_certs: false
    register: auth_response

  - name: Get GRID tenant accounts
    uri:
      url: "https://{{ SG_ADMIN_NODE }}/api/v3/grid/accounts?includeMarker=true"
      method: GET
      headers: {
        "accept":              "application/json",
        "Authorization":       "{{ auth_response.json.data }}"
      }
      validate_certs: false
    register: grid_tenants

  - name: Print GRID tenants
    debug:
      msg:
        - "Tenant:             {{ item.name }}"
        - "ID:                 {{ item.id }}"
        - "Capabilities:       {{ item.capabilities }}"
        - "Policy:             {{ item.policy }}"
    with_items:
      - "{{ grid_tenants.json.data }}"
    loop_control:
      label: "{{ item.id }}"
