#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        03_get_bucket_details.yml 
# Author:       Adrian Bronder
# Date:         2020-06-30
# Description:  Get tenant information
#               with Ansible and REST APIs
#
# Modules:      URI (calling GRID REST APIs)
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://<GRID Admin>/ui/apidocs.html
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "username":            "{{ SG_ADMIN_USER }}",
        "password":            "{{ SG_ADMIN_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: grid_auth_response

  - name: Get GRID tenant accounts
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/grid/accounts"
      method:                  GET
      validate_certs:          false
      headers: {
        "accept":              "application/json",
        "Authorization":       "{{ grid_auth_response.json.data }}"
      }
    register: grid_tenants

  - name: Get tenant by name
    set_fact:
      selected_tenant: '{{ grid_tenants.json.data |
                           selectattr("name", "equalto", TENANT) |
                           list }}'

  - name: Check for unique tenant
    fail:
      msg: "Unique tenant ID for given name '{{ TENANT }}' not found"
    when:
      ( selected_tenant | length ) != 1

  - name: Get tenant authorization token
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "accountId":           "{{ selected_tenant.0.id }}",
        "username":            "root",
        "password":            "{{ TENANT_ROOT_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: tenant_auth_response

  - name: Get S3 buckest from tenant
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/org/containers"
      method:                  GET
      validate_certs:          false
      headers: {
        "accept":              "application/json",
        "Authorization":       "{{ tenant_auth_response.json.data }}"
      }
    register: tenant_buckets

  - name: Print tenant buckets
    debug:
      msg:
        - "Tenant:             {{ TENANT }}"
        - "Name:               {{ item.name }}"
        - "Create Time:        {{ item.creationTime }}"
    with_items:
      - "{{ tenant_buckets.json.data }}"
    loop_control:
      label: "{{ item.name }}"
