#!/usr/bin/env ansible-playbook

##################################
# --->>> WORK IN PROGRESS <<<--- #
##################################

################################################################################
#
# Title:        31_create_s3bucket.yml 
# Author:       Adrian Bronder
# Date:         2020-06-18
# Description:  Create an S3 bucket on tenant
#               with Ansible modules
#
# Modules:      nac_sg_org_container
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://galaxy.ansible.com/netapp/storagegrid
#
# Built-in help:
# ansible-doc netapp.storagegrid.nac_sg_org_container
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ auth_response.json.data }}"
      validate_certs:          false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url: "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method: POST
      body: {
        "username":            "{{ SG_ADMIN_USER }}",
        "password":            "{{ SG_ADMIN_PASSWORD }}",
        "cookie":              false,
        "csrfToken":           false
      }
      body_format: json
      validate_certs: false
    register: auth_response

  - name: Get tenant account ID
    uri:
      url: "https://{{ SG_ADMIN_NODE }}/api/v3/grid/accounts?includeMarker=true"
      method: GET
      headers: {
        "accept":              "application/json",
        "Authorization":       "{{ auth_response.json.data }}"
      }
      validate_certs: false
    register: grid_tenants

  - name: Get tenant ID by name
    set_fact:
      tenant_id: '{{ grid_tenants.json.data | selectattr("name", "equalto", "LOD_ANSIBLE_TEST")| list }}'

  - name: print tenant ID
    debug:
      msg: "{{ tenant_id }}"
