---
# tasks file for ontap_svm
- name: Check for mandatory variables
  fail:
    msg: "You must pass the 'ontap_svm_name' variable"
  when:
    ontap_svm_name is undefined
  tags:
    - always

- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   Never
  tags:
    - always
  no_log: true

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        ontap_svm_obj: "{{ ontap_svm_obj | combine(item, recursive=True) }}"
      loop:
        "{{ svms | list }}"
      when:
        - item.name == ontap_svm_name
  tags:
    - source_inventory

- name: Create SVM
  na_ontap_svm:
    state:                        present
    name:                         "{{ ontap_svm_name }}"
    language:                     "{{ ontap_svm_obj.language }}"
    comment:                      "{{ ontap_svm_obj.comment }}"
    ipspace:                      "{{ ontap_svm_obj.ipspace.name }}"
    snapshot_policy:              "{{ ontap_svm_obj.snapshot_policy.name }}"
    <<: *ontap_login
  tags:
    - create_all
    - create_ontap_svm
    - modify_ontap_svm

- name: Create Management LIF
  include_role:
    name: ontap_ip_interface
  when:
    - ontap_ip_interface_name is defined
  tags:
    - create_all
    - create_ontap_svm

- name: Configure DNS
  na_ontap_dns:
    state:                        present
    vserver:                      "{{ ontap_svm_name }}"
    domains:                      "{{ ontap_svm_obj.dns.domains }}"
    nameservers:                  "{{ ontap_svm_obj.dns.servers }}"
    <<: *ontap_login
  tags:
    - create_all
    - create_ontap_svm
    - modify_ontap_svm

- name: Delete SVM
  na_ontap_svm:
    state:                        absent
    name:                         "{{ ontap_svm_name }}"
    <<: *ontap_login
  tags:
    - never
    - delete_all
    - delete_ontap_svm
