---
# tasks file for ontap_svm

- name: Set Connection Details
  ansible.builtin.set_fact:
    ontap_login: &ontap_login
      hostname:                   "{{ ontap_hostname }}"
      username:                   "{{ ontap_username }}"
      password:                   "{{ ontap_password }}"
      https:                      true
      validate_certs:             false
      use_rest:                   never
  tags:
    - always
  no_log: true

- name: Source Inventory Information
  block:
    - name: Find SVM
      ansible.builtin.set_fact:
        svm: "{{ item }}"
      loop:
        "{{ svms | list}}"
      when:
        - item.name == svm_name
    - name: Include HostVars
      ansible.builtin.set_fact:
        "{{ item }}": "{{ svm[item] }}"
      loop:
        "{{ svm | list }}"
      when:
        - svm[item]
  tags:
    - "source_inventory"

- name: Create SVM
  na_ontap_svm:
    state:                        present
    name:                         "{{ name }}"
    language:                     "{{ language }}"
    comment:                      "{{ comment }}"
    ipspace:                      "{{ ipspace.name }}"
    snapshot_policy:              "{{ snapshot_policy.name }}"
    <<: *ontap_login
  tags:
    - create_ontap_svm
    - modify_ontap_svm

- name: Create LIFs
  na_ontap_interface:
    state:                        present
    interface_name:               "{{ item.name }}"
    vserver:                      "{{ name }}"
    address:                      "{{ item.ip.address }}"
    netmask:                      "{{ item.ip.netmask }}"
    service_policy:               "{{ item.service_policy.name }}"
    home_node:                    "{{ item.location.home_node.name }}"
    home_port:                    "{{ item.location.home_port.name }}"
# FIXME - This one is ugly, but "role" must be provided as long as we have to use ZAPI here
    role:                         "data"
    <<: *ontap_login
  loop:
    "{{ ip_interfaces | list }}"
  tags:
    - create_ontap_svm

- name: Configure DNS
  na_ontap_dns:
    state:                        present
    vserver:                      "{{ name }}"
    domains:                      "{{ dns.domains }}"
    nameservers:                  "{{ dns.servers }}"
    <<: *ontap_login
  tags:
    - create_ontap_svm
    - modify_ontap_svm

- name: Delete SVM
  na_ontap_svm:
    state:                        absent
    name:                         "{{ svm_name }}"
    <<: *ontap_login
  tags:
    - delete_ontap_svm
