---
- name: Create volume on primary SVM
  netapp.ontap.na_ontap_volume:
    state:                 present
    name:                  "{{ PRI_SVM }}_iscsilin_01"
    vserver:               "{{ PRI_SVM }}"
    size:                  "{{ VOL_SIZE }}"
    size_unit:             b
    aggregate_name:        "{{ PRI_AGGR }}"
    comment:               Created with Ansible
    space_guarantee:       volume
    policy:                default
    volume_security_style: unix
    hostname:              "{{ PRI_CLU }}"
    username:              "{{ PRI_CLU_USER }}"
    password:              "{{ PRI_CLU_PASS }}"
    https:                 true
    validate_certs:        false

- name: Create LUN on primary SVM
  netapp.ontap.na_ontap_lun:
    state:                 present
    name:                  "{{ PRI_SVM }}_lunlin_01"
    vserver:               "{{ PRI_SVM }}"
    flexvol_name:          "{{ PRI_SVM }}_iscsilin_01"
    size:                  "{{ LUN_SIZE }}"
    size_unit:             b
    space_reserve:         true
    ostype:                windows
    hostname:              "{{ PRI_CLU }}"
    username:              "{{ PRI_CLU_USER }}"
    password:              "{{ PRI_CLU_PASS }}"
    https:                 true
    validate_certs:        false

- name: Create igroup on primary SVM
  na_ontap_igroup:
    state: present
    name:                  "{{ PRI_SVM }}_linig_01"
    vserver:               "{{ PRI_SVM }}"
    initiator_group_type:  iscsi
    ostype:                linux
    initiator:             "{{ LIN_IQN }}"
    hostname:              "{{ PRI_CLU }}"
    username:              "{{ PRI_CLU_USER }}"
    password:              "{{ PRI_CLU_PASS }}"
    https:                 true
    validate_certs:        false

- name: Map LUN to igroup
  na_ontap_lun_map:
    state: present
    vserver:               "{{ PRI_SVM }}"
    initiator_group_name:  "{{ PRI_SVM }}_linig_01"
    path:                  "/vol/{{ PRI_SVM }}_iscsilin_01/{{ PRI_SVM }}_lunlin_01"
    hostname:              "{{ PRI_CLU }}"
    username:              "{{ PRI_CLU_USER }}"
    password:              "{{ PRI_CLU_PASS }}"
    https:                 true
    validate_certs:        false

