#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        11_create_ipspace_pri_clu.yml 
# Author:       Adrian Bronder
# Date:         2020-09-09
# Description:  Create an IPspace on the primary cluster
#               with Ansible modules
#
# Modules:      na_ontap_ipspace
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_ipspace
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create IPspace on the primary cluster
    na_ontap_ipspace:
      state:                 present
      name:                  "{{ IPSPACE }}"
      <<: *input
