#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        14_create_bcdomainmgmt_pri_clu.yml 
# Author:       Adrian Bronder
# Date:         2020-09-09
# Description:  Create a broadcast domain for mgmt LIFs on the primary cluster
#               with Ansible modules
#
# Modules:      na_ontap_broadcast_domain
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_broadcast_domain
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create broadcast domain on the primary cluster
    na_ontap_broadcast_domain:
      state:                 present
      name:                  "{{ BCDOMAIN_MGMT }}"
      mtu:                   1500
      ipspace:               "{{ IPSPACE }}"
      ports:
        - "{{ PRI_CLU_NODE1 }}:{{ VLAN_PORT }}-{{ VLAN_MGMT }}"
        - "{{ PRI_CLU_NODE2 }}:{{ VLAN_PORT }}-{{ VLAN_MGMT }}"
      <<: *input
