#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        30_create_cifsshare_all.yml
# Author:       Adrian Bronder
# Date:         2020-06-19
# Description:  Create CIFS share on existing SVM (end-to-end)
#               with Ansible modules
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create volume on primary SVM
    na_ontap_volume:
      state:                 present
      name:                  "{{ PRI_SVM }}_cifs_01"
      vserver:               "{{ PRI_SVM }}"
      size:                  "{{ VOL_SIZE }}"
      size_unit:             b
      aggregate_name:        "{{ PRI_AGGR }}"
      comment:               Created with Ansible
      space_guarantee:       volume
      policy:                default
      junction_path:         "/{{ PRI_SVM }}_cifs_01"
      volume_security_style: ntfs
      <<: *input

  - name: Create qtree on primary SVM
    na_ontap_qtree:
      state:                 present
      name:                  "cifs_01"
      vserver:               "{{ PRI_SVM }}"
      flexvol_name:          "{{ PRI_SVM }}_cifs_01"
      security_style:        ntfs
      <<: *input

  - name: Create CIFS share on primary SVM
    na_ontap_cifs:
      state:                 present
      share_name:            "share_01"
      vserver:               "{{ PRI_SVM }}"
      path:                  "/{{ PRI_SVM }}_cifs_01/cifs_01/"
      <<: *input

