#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        33_create_cifsshare_pri_svm.yml
# Author:       Adrian Bronder
# Date:         2020-20-03
# Description:  Create CIFS share on primary SVM
#               with Ansible modules
#
# Modules:      na_ontap_cifs
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_cifs
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create CIFS share on primary SVM
    na_ontap_cifs:
      state:                 present
      name:                  "share_01"
      vserver:               "{{ PRI_SVM }}"
      path:                  "/{{ PRI_SVM }}_cifs_01/cifs_01/"
      <<: *input
