#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        42_create_iscsiwinlun_pri_svm.yml
# Author:       Adrian Bronder
# Date:         2020-06-16
# Description:  Create lun on primary SVM
#               with Ansible modules
#
# Modules:      na_ontap_lun
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_lun
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create lun on primary SVM
    na_ontap_lun:
      state:                 present
      name:                  "{{ PRI_SVM }}_lunwin_01"
      vserver:               "{{ PRI_SVM }}"
      flexvol_name:          "{{ PRI_SVM }}_iscsiwin_01"
      size:                  "{{ LUN_SIZE }}"
      size_unit:             b
      space_reserve:         true
      ostype:                windows
      <<: *input
