#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        49_create_linlunmap_pri_svm.yml
# Author:       Adrian Bronder
# Date:         2020-06-16
# Description:  Create lun mapping on primary SVM
#               with Ansible modules
#
# Modules:      na_ontap_lun_map
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_lun_map
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - ../global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create igroup on primary SVM
    na_ontap_lun_map:
      state: present
      vserver:               "{{ PRI_SVM }}"
      initiator_group_name:  "{{ PRI_SVM }}_linig_01"
      path:                  "/vol/{{ PRI_SVM }}_iscsilin_01/{{ PRI_SVM }}_lunlin_01"
      <<: *input
